WATCOWebBBSR/Controllers/DashBoardController.cs
using ODLSystem.Library.Common.EntityModel;
using System;
using System.Web.Mvc;

namespace WATCOWebBBSR.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        public DashBoardController()
        {

        }
        string cityName = "";//!String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];

        string name = "Ratikant";
        public ActionResult Container()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            return View();
        }
        // GET: Water Supply DashBoard
        public ActionResult WaterSupplyInfo()
        {
            ViewBag.Region = cityName;//(string)Session["Region"];
            return View();
        }
        [HttpPost]
        public ActionResult GetSummaryWaterSupply()
        {
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            return Json(cInfo);
        }
        // GET: Consumer Information
        public ActionResult ConsumerInfo()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            var serializedObj = Newtonsoft.Json.JsonConvert.SerializeObject(cInfo);
            ViewBag.CInfo = ((dynamic)Newtonsoft.Json.JsonConvert.DeserializeObject(serializedObj));
            return View();
        }
        // GET: Asset & OEM Activity
        public ActionResult AssetOEMActivity()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var aoemInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardAssets().GetAssetDashboardInformation();
            var serializedObj = Newtonsoft.Json.JsonConvert.SerializeObject(aoemInfo);
            ViewBag.AOEMnfo = ((dynamic)Newtonsoft.Json.JsonConvert.DeserializeObject(serializedObj));
            return View();
        }
        // GET: User Charges Info
        public ActionResult UserChargeInfo()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            return View();
        }
        // GET: Jalsathi Performance
        public ActionResult JalSathiPerform()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            return View();
        }
        // GET: Water Quality Monitoring
        public ActionResult WaterQualityMonitor()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            return View();
        }
        // GET: Consumer Grievance
        public ActionResult ConsumerGrievance()
        {
            cityName = !String.IsNullOrEmpty(CoreUserAuthorizationDetail.SelectedCityName) ? CoreUserAuthorizationDetail.SelectedCityName : (string)Session["Region"];
            ViewBag.Region = cityName;//(string)Session["Region"];
            var cInfo = new ODLSystem.BusinessLayer.Dashboard.DashboardConsumers().GetConsumerDashboardInformation();
            return View();
        }
    }
}

WATCOWebBBSR/Views/DashBoard/ConsumerGrievance.cshtml
@{
    ViewBag.Title = "Consumer Grievance";
    ViewBag.SubTitle = "[ Region- " + (string)ViewBag.Region + " ]";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu {
    @Scripts.Render("~/Scripts/DashBoard/ConsumerGriev/menu")
}
@Styles.Render("~/AdminLTE/plugins/morris/css")
@Styles.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/css")
<div class="row">
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>12</h3>
                <p>No. Of Complaints Received Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-waterdrop"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-green">
            <div class="inner">
                <h3>10</h3>
                <p>No. Of Complaints Resolved Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>71</h3>
                <p>No. Of Complaints Received This Month</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>61</h3>
                <p>No. Of Complaints Resolved This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-ios-analytics-outline"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>No Water Supply</h3>
                <p>Highest Complaint Category</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-lime-active">
            <div class="inner">
                <h3>Water Quality</h3>
                <p>Least Complaint Category</p>
            </div>
            <div class="icon">
                <i class="fa fa-user-times"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs pull-right">
                    <li class="active"><a href="#bar-chart" data-toggle="tab">Bar</a></li>
                    <li><a href="#stack-chart" data-toggle="tab">Stack</a></li>
                    <li class="pull-left header">
                        <i class="fa fa-inbox"></i>Weekly Complaints Status
                    </li>
                </ul>
                <div class="tab-content no-padding">
                    <div class="chart tab-pane active" id="bar-chart" style="position: relative; height: 300px;"></div>
                    <div class="chart tab-pane" id="stack-chart" style="position: relative; height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    @Scripts.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/js")
    @Scripts.Render("~/AdminLTE/plugins/knob/js")
    @Scripts.Render("~/AdminLTE/plugins/raphael/js")
    @Scripts.Render("~/AdminLTE/plugins/morris/js")
    @Scripts.Render("~/Scripts/DashBoard/ConsumerGriev/data")
}

WATCOWebBBSR/Views/DashBoard/Container.cshtml
@{
    ViewBag.Title = "Dashboard Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu {
    @Scripts.Render("~/Scripts/DashBoard/Container/menu")
}
<div class="row">
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <p>Water Supply</p>
                <h3>9500 (Klt.)</h3>
                <p>Supplied Today</p>
            </div>
            <div class="icon">
                <i class="fa fa-tint"></i>
            </div>
            <a href="@Url.Action("WaterSupplyInfo", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-green">
            <div class="inner">
                <p>Consumer</p>
                <h3>439</h3>
                <p>Total Consumer</p>
            </div>
            <div class="icon">
                <i class="fa fa-user"></i>
            </div>
            <a href="@Url.Action("ConsumerInfo", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-yellow">
            <div class="inner">
                <p>Assets</p>
                <h3>532</h3>
                <p>No. Of Assets</p>
            </div>
            <div class="icon">
                <i class="ion ion-ios-analytics-outline"></i>
            </div>
            <a href="@Url.Action("AssetOEMActivity", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-red">
            <div class="inner">
                <p>Quality & Test</p>
                <h3>50</h3>
                <p>Tests Conducted Today</p>
            </div>
            <div class="icon">
                <i class="fa fa-signal"></i>
            </div>
            <a href="@Url.Action("WaterQualityMonitor", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-blue">
            <div class="inner">
                <p>Consumer Grievance</p>
                <h3>71</h3>
                <p>Complaints Received</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a href="@Url.Action("ConsumerGrievance", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-green-gradient">
            <div class="inner">
                <p>JalSathi</p>
                <h3>338359(INR)</h3>
                <p>Collected</p>
            </div>
            <div class="icon">
                <i class="fa fa-rupee"></i>
            </div>
            <a href="@Url.Action("JalsathiPerform", "DashBoard")" class="small-box-footer">More Information <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    @Scripts.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/js")
    @Scripts.Render("~/AdminLTE/plugins/sparkline/js")
    @Scripts.Render("~/AdminLTE/plugins/knob/js")
    @Scripts.Render("~/AdminLTE/plugins/raphael/js")
    @Scripts.Render("~/AdminLTE/plugins/morris/js")
}

WATCOWebBBSR/Views/DashBoard/JalSathiPerform.cshtml
@{
    ViewBag.Title = "JalSathi Perfomance";
    ViewBag.SubTitle = "[ Region- " + (string)ViewBag.Region + " ]";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu {
    @Scripts.Render("~/Scripts/DashBoard/Jalsathi/menu")
}
@Styles.Render("~/AdminLTE/plugins/morris/css")
@Styles.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/css")
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>7</h3>
                <p>No. Of Jalsathi Engaged</p>
            </div>
            <div class="icon">
                <i class="ion ion-waterdrop"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-green">
            <div class="inner">
                <h3>0</h3>
                <p>No. Of Bill Collected By Jalsathi Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>0</h3>
                <p>Bill Amount Collected By Jalsathi Today (Rs.)</p>
            </div>
            <div class="icon">
                <i class="fa fa-rupee"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>1690</h3>
                <p>No Of Bill Collected By Jalsathi This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-ios-analytics-outline"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>338359</h3>
                <p>Bill Amount Collected This Month</p>
            </div>
            <div class="icon">
                <i class="fa fa-rupee"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-lime-active">
            <div class="inner">
                <h3>0</h3>
                <p>Water Sample Tested Today</p>
            </div>
            <div class="icon">
                <i class="fa fa-user"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-green-gradient">
            <div class="inner">
                <h3>189</h3>
                <p>Water Sample Tested This Month</p>
            </div>
            <div class="icon">
                <i class="fa fa-rupee"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>20697</h3>
                <p>Incentive Paid This Month</p>
            </div>
            <div class="icon">
                <i class="fa fa-rupee"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs pull-right">
                    <li class="active"><a href="#bar-chart" data-toggle="tab">Bar</a></li>
                    <li><a href="#donut-chart" data-toggle="tab">Donut</a></li>
                    <li class="pull-left header">
                        <i class="fa fa-inbox"></i>Jalsathi Performance
                    </li>
                </ul>
                <div class="tab-content no-padding">
                    <div class="chart tab-pane active" id="bar-chart" style="position: relative; height: 350px;"></div>
                    <div class="chart tab-pane" id="donut-chart" style="position: relative; height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    @Scripts.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/js")
    @Scripts.Render("~/AdminLTE/plugins/knob/js")
    @Scripts.Render("~/AdminLTE/plugins/raphael/js")
    @Scripts.Render("~/AdminLTE/plugins/morris/js")
    @Scripts.Render("~/Scripts/DashBoard/Jalsathi/data")
}

WATCOWebBBSR/Views/DashBoard/UserChargeInfo.cshtml
@{
    ViewBag.Title = "UserChargeInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UserChargeInfo</h2>

WATCOWebBBSR/Views/DashBoard/WaterQualityMonitor.cshtml
@{
    ViewBag.Title = "Water Quality Monitor";
    ViewBag.SubTitle = "[ Region- " + (string)ViewBag.Region + " ]";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu {
    @Scripts.Render("~/Scripts/DashBoard/WaterQuality/menu")
}
@Styles.Render("~/AdminLTE/plugins/morris/css")
@Styles.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/css")
<div class="row">
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>50</h3>
                <p>No. Of Samples Collected Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-waterdrop"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-green">
            <div class="inner">
                <h3>50</h3>
                <p>No. Of Sample Tested Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>2</h3>
                <p>No. Of Sample Failed Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>50</h3>
                <p>No. Of Sample Collected This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-lime-active">
            <div class="inner">
                <h3>50</h3>
                <p>No Of Sample Tested This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>30</h3>
                <p>No Of Sample Failed This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>    
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>Ishaneswar</h3>
                <p>Highest Failed Zone</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <div class="small-box bg-lime-active">
            <div class="inner">
                <h3>Ishaneswar</h3>
                <p>Highest Success Zone</p>
            </div>
            <div class="icon">
                <i class="fa fa-users"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
</div>
@*<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs pull-right">
                    <li class="active"><a href="#bar-chart" data-toggle="tab">Bar</a></li>
                    <li><a href="#stack-chart" data-toggle="tab">Stack</a></li>
                    <li class="pull-left header">
                        <i class="fa fa-inbox"></i>Weekly Complaints Status
                    </li>
                </ul>
                <div class="tab-content no-padding">
                    <div class="chart tab-pane active" id="bar-chart" style="position: relative; height: 300px;"></div>
                    <div class="chart tab-pane" id="stack-chart" style="position: relative; height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>*@
@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    @Scripts.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/js")
    @Scripts.Render("~/AdminLTE/plugins/knob/js")
    @Scripts.Render("~/AdminLTE/plugins/raphael/js")
    @Scripts.Render("~/AdminLTE/plugins/morris/js")
    @Scripts.Render("~/Scripts/DashBoard/WaterQuality/data")
}

WATCOWebBBSR/Views/DashBoard/WaterSupplyInfo.cshtml
@{
    ViewBag.Title = "Water Supply Information";
    ViewBag.SubTitle = "[ Region- " + (string)ViewBag.Region + " ]";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Menu {
    @Scripts.Render("~/Scripts/DashBoard/WaterSupply/menu")
}
@Styles.Render("~/AdminLTE/plugins/morris/css")
@Styles.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/css")
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-light-blue">
            <div class="inner">
                <h3>9500 (KLt.)</h3>
                <p>Total Water Supply Today</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-green">
            <div class="inner">
                <h3>64300 (KLt.)</h3>
                <p>Total Water Supply This Week</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>257200 (KLt.)</h3>
                <p>Total Water Supply This Month</p>
            </div>
            <div class="icon">
                <i class="ion ion-waterdrop"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>4</h3>
                <p>Reading From Bulk Meter</p>
            </div>
            <div class="icon">
                <i class="ion ion-ios-analytics-outline"></i>
            </div>
            <a class="small-box-footer"><i class="fa fa-cog disabled"></i></a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs pull-right">
                    <li class="active"><a href="#line-chart" data-toggle="tab">Line</a></li>
                    <li><a href="#donut-chart" data-toggle="tab">Donut</a></li>
                    <li class="pull-left header">
                        <i class="fa fa-inbox"></i>Weekly Water Flow Status
                    </li>
                </ul>
                <div class="tab-content no-padding">
                    <div class="chart tab-pane active" id="line-chart" style="position: relative; height: 300px;"></div>
                    <div class="chart tab-pane" id="donut-chart" style="position: relative; height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    @Scripts.Render("~/AdminLTE/plugins/bootstrap-wysihtml5/js")
    @Scripts.Render("~/AdminLTE/plugins/knob/js")
    @Scripts.Render("~/AdminLTE/plugins/raphael/js")
    @Scripts.Render("~/AdminLTE/plugins/morris/js")
    @Scripts.Render("~/AdminLTE/plugins/datepicker/js")
    @Scripts.Render("~/Scripts/DashBoard/WaterSupply/data")
}